apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-east1-docker.pkg.dev/csci-5409-cloud-computing/container1/my-app:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: pv-volume
              mountPath: /app/Anubhooti_PV_dir
      volumes:
        - name: pv-volume
          persistentVolumeClaim:
            claimName: my-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer
