services:
  container1:
    image: anubhootipathak/container1:tagname
    ports:
      - 6000:6000
    depends_on:
      - container2
    volumes:
      - ./:/data

  container2:
    image: anubhootipathak/container2:tagname
    volumes:
      - ./:/data
