apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-east1-docker.pkg.dev/csci-5409-cloud-computing/container2/my-app:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
